# Generated by Django 4.0.1 on 2022-01-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('datanascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=50)),
                ('hobby', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
